# Generated by Django 2.2 on 2023-08-11 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 4, 37, 3, 797247)),
        ),
    ]
